name: test-java
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Obtener código y chequear repo
      uses: actions/checkout@v2

    - name: Listar archivos y directorios
      run: ls -R

    - name: Configurar Java con Temurin JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos a mvnw
      run: chmod +x mvnw

    - name: Test code Java Spring Boot
      run: |
        ./mvnw clean test